var files_dup =
[
    [ "m_assign_variables.fpp.f90", "m__assign__variables_8fpp_8f90.html", "m__assign__variables_8fpp_8f90" ],
    [ "m_boundary_common.fpp.f90", "m__boundary__common_8fpp_8f90.html", "m__boundary__common_8fpp_8f90" ],
    [ "m_boundary_conditions.fpp.f90", "m__boundary__conditions_8fpp_8f90.html", "m__boundary__conditions_8fpp_8f90" ],
    [ "m_check_ib_patches.fpp.f90", "m__check__ib__patches_8fpp_8f90.html", "m__check__ib__patches_8fpp_8f90" ],
    [ "m_check_patches.fpp.f90", "m__check__patches_8fpp_8f90.html", "m__check__patches_8fpp_8f90" ],
    [ "m_checker.fpp.f90", "m__checker_8fpp_8f90.html", "m__checker_8fpp_8f90" ],
    [ "m_checker_common.fpp.f90", "m__checker__common_8fpp_8f90.html", "m__checker__common_8fpp_8f90" ],
    [ "m_chemistry.fpp.f90", "m__chemistry_8fpp_8f90.html", "m__chemistry_8fpp_8f90" ],
    [ "m_compute_levelset.fpp.f90", "m__compute__levelset_8fpp_8f90.html", "m__compute__levelset_8fpp_8f90" ],
    [ "m_constants.fpp.f90", "m__constants_8fpp_8f90.html", "m__constants_8fpp_8f90" ],
    [ "m_data_output.fpp.f90", "m__data__output_8fpp_8f90.html", "m__data__output_8fpp_8f90" ],
    [ "m_derived_types.fpp.f90", "m__derived__types_8fpp_8f90.html", "m__derived__types_8fpp_8f90" ],
    [ "m_finite_differences.fpp.f90", "m__finite__differences_8fpp_8f90.html", "m__finite__differences_8fpp_8f90" ],
    [ "m_global_parameters.fpp.f90", "m__global__parameters_8fpp_8f90.html", "m__global__parameters_8fpp_8f90" ],
    [ "m_helper.fpp.f90", "m__helper_8fpp_8f90.html", "m__helper_8fpp_8f90" ],
    [ "m_helper_basic.fpp.f90", "m__helper__basic_8fpp_8f90.html", "m__helper__basic_8fpp_8f90" ],
    [ "m_ib_patches.fpp.f90", "m__ib__patches_8fpp_8f90.html", "m__ib__patches_8fpp_8f90" ],
    [ "m_icpp_patches.fpp.f90", "m__icpp__patches_8fpp_8f90.html", "m__icpp__patches_8fpp_8f90" ],
    [ "m_initial_condition.fpp.f90", "m__initial__condition_8fpp_8f90.html", "m__initial__condition_8fpp_8f90" ],
    [ "m_model.fpp.f90", "m__model_8fpp_8f90.html", "m__model_8fpp_8f90" ],
    [ "m_mpi_common.fpp.f90", "m__mpi__common_8fpp_8f90.html", "m__mpi__common_8fpp_8f90" ],
    [ "m_mpi_proxy.fpp.f90", "m__mpi__proxy_8fpp_8f90.html", "m__mpi__proxy_8fpp_8f90" ],
    [ "m_perturbation.fpp.f90", "m__perturbation_8fpp_8f90.html", "m__perturbation_8fpp_8f90" ],
    [ "m_phase_change.fpp.f90", "m__phase__change_8fpp_8f90.html", "m__phase__change_8fpp_8f90" ],
    [ "m_start_up.fpp.f90", "m__start__up_8fpp_8f90.html", "m__start__up_8fpp_8f90" ],
    [ "m_variables_conversion.fpp.f90", "m__variables__conversion_8fpp_8f90.html", "m__variables__conversion_8fpp_8f90" ],
    [ "m_compile_specific.f90", "m__compile__specific_8f90.html", "m__compile__specific_8f90" ],
    [ "m_delay_file_access.f90", "m__delay__file__access_8f90.html", "m__delay__file__access_8f90" ],
    [ "m_nvtx.f90", "m__nvtx_8f90.html", "m__nvtx_8f90" ],
    [ "m_precision_select.f90", "m__precision__select_8f90.html", "m__precision__select_8f90" ],
    [ "m_grid.f90", "m__grid_8f90.html", "m__grid_8f90" ],
    [ "p_main.f90", "p__main_8f90.html", "p__main_8f90" ]
];