var searchData=
[
  ['case_0',['Running an Example Case',['../md_getting-started.html#autotoc_md124',1,'']]],
  ['case_20files_1',['Case Files',['../md_case.html',1,'']]],
  ['case_2emd_2',['case.md',['../case_8md.html',1,'']]],
  ['cases_3',['Cases',['../md_examples.html',1,'Example Cases'],['../md_running.html#autotoc_md161',1,'Restarting Cases']]],
  ['cavity_20problem_202d_4',['Lid-Driven Cavity Problem (2D)',['../md_examples.html#autotoc_md78',1,'']]],
  ['centerline_20velocities_5',['Centerline Velocities',['../md_examples.html#autotoc_md80',1,'']]],
  ['cfl_20dt_202d_6',['2D IBM CFL dt (2D)',['../md_examples.html#autotoc_md63',1,'']]],
  ['change_20model_7',['11. Phase Change Model',['../md_case.html#autotoc_md25',1,'']]],
  ['characteristic_20boundary_20conditions_8',['Generalized Characteristic Boundary conditions',['../md_case.html#autotoc_md33',1,'']]],
  ['cli_9',['Docker CLI',['../md_docker.html#autotoc_md41',1,'']]],
  ['clusters_20via_20apptainer_20singularity_10',['Using Supercomputers/Clusters via Apptainer/Singularity',['../md_docker.html#autotoc_md44',1,'']]],
  ['code_20api_20documentation_11',['Code/API Documentation',['../md_readme.html#autotoc_md153',1,'']]],
  ['coded_20patches_12',['Hard Coded Patches',['../md_case.html#autotoc_md10',1,'']]],
  ['command_20line_20arguments_13',['(Optional) Accepting command line arguments',['../md_case.html#autotoc_md4',1,'']]],
  ['compiler_20agnostic_20tools_14',['Compiler agnostic tools',['../md_gpuParallelization.html#autotoc_md140',1,'']]],
  ['compiler_20documentation_15',['Compiler Documentation',['../md_gpuParallelization.html#autotoc_md149',1,'']]],
  ['compiler_20options_16',['NVHPC Compiler Options',['../md_gpuParallelization.html#autotoc_md145',1,'']]],
  ['compiler_20tools_17',['Cray Compiler Tools',['../md_gpuParallelization.html#autotoc_md142',1,'']]],
  ['component_20inert_20shock_20tube_18',['1D Multi-Component Inert Shock Tube',['../md_examples.html#autotoc_md102',1,'']]],
  ['component_20reactive_20shock_20tube_19',['1D Multi-Component Reactive Shock Tube',['../md_examples.html#autotoc_md70',1,'']]],
  ['computation_20macros_20',['Computation Macros',['../md_gpuParallelization.html#autotoc_md131',1,'']]],
  ['computational_20domain_21',['2. Computational Domain',['../md_case.html#autotoc_md7',1,'']]],
  ['condition_22',['Condition',['../md_examples.html#autotoc_md69',1,'Final Condition'],['../md_examples.html#autotoc_md79',1,'Final Condition'],['../md_examples.html#autotoc_md95',1,'Final Condition'],['../md_examples.html#autotoc_md106',1,'Final Condition'],['../md_examples.html#autotoc_md55',1,'Initial Condition'],['../md_examples.html#autotoc_md66',1,'Initial Condition'],['../md_examples.html#autotoc_md71',1,'Initial Condition'],['../md_examples.html#autotoc_md85',1,'Initial Condition'],['../md_examples.html#autotoc_md92',1,'Initial Condition'],['../md_examples.html#autotoc_md103',1,'Initial Condition']]],
  ['condition_20and_20linear_20theory_23',['Condition and Linear Theory',['../md_examples.html#autotoc_md62',1,'Final Condition and Linear Theory'],['../md_examples.html#autotoc_md97',1,'Final Condition and Linear Theory']]],
  ['condition_20and_20result_24',['Initial Condition and Result',['../md_examples.html#autotoc_md88',1,'']]],
  ['condition_20density_25',['Condition Density',['../md_examples.html#autotoc_md74',1,'Final Condition (Density)'],['../md_examples.html#autotoc_md90',1,'Final Condition (Density)']]],
  ['condition_20patches_26',['Boundary Condition Patches',['../md_case.html#autotoc_md17',1,'']]],
  ['conditions_27',['Density Initial and Final Conditions',['../md_examples.html#autotoc_md76',1,'']]],
  ['conditions_28',['conditions',['../md_case.html#autotoc_md32',1,'Boundary conditions'],['../md_case.html#autotoc_md33',1,'Generalized Characteristic Boundary conditions']]],
  ['conservative_20variables_20ordering_29',['Conservative Variables Ordering',['../md_case.html#autotoc_md36',1,'']]],
  ['constant_20time_20stepping_30',['Constant Time-Stepping',['../md_case.html#autotoc_md18',1,'']]],
  ['containers_31',['Containers',['../md_docker.html',1,'Containers'],['../md_docker.html#autotoc_md42',1,'Details on Running Containers'],['../md_getting-started.html#autotoc_md122',1,'Using Containers']]],
  ['continuous_20benchmarks_32',['Continuous Benchmarks',['../continuousBenchmarks.html',1,'Continuous Benchmarks'],['../continuousBenchmarks.html#autotoc_md1',1,'Continuous Benchmarks']]],
  ['control_20macros_33',['Data Control Macros',['../md_gpuParallelization.html#autotoc_md133',1,'']]],
  ['coordinates_34',['16. Cylindrical Coordinates',['../md_case.html#autotoc_md30',1,'']]],
  ['coordinates_35',['Visualizing data in cylindrical coordinates',['../md_visualization.html#autotoc_md168',1,'']]],
  ['cpu_36',['CPU',['../expectedPerformance.html#autotoc_md112',1,'IBM Power9 CPU'],['../expectedPerformance.html#autotoc_md117',1,'IBM Power9 CPU']]],
  ['cray_20compiler_20tools_37',['Cray Compiler Tools',['../md_gpuParallelization.html#autotoc_md142',1,'']]],
  ['cray_20general_20options_38',['Cray General Options',['../md_gpuParallelization.html#autotoc_md143',1,'']]],
  ['cray_20openacc_20options_39',['Cray OpenACC Options',['../md_gpuParallelization.html#autotoc_md144',1,'']]],
  ['creating_20tests_40',['Creating Tests',['../md_testing.html#autotoc_md164',1,'']]],
  ['customizing_20the_20script_41',['Step 2: Customizing the script',['../md_visualization.html#autotoc_md173',1,'']]],
  ['cylindrical_20coordinates_42',['16. Cylindrical Coordinates',['../md_case.html#autotoc_md30',1,'']]],
  ['cylindrical_20coordinates_43',['Visualizing data in cylindrical coordinates',['../md_visualization.html#autotoc_md168',1,'']]]
];
