var searchData=
[
  ['case_0',['Running an Example Case',['../md_getting-started.html#autotoc_md123',1,'']]],
  ['case_20files_1',['Case Files',['../md_case.html',1,'']]],
  ['case_2emd_2',['case.md',['../case_8md.html',1,'']]],
  ['cases_3',['Cases',['../md_examples.html',1,'Example Cases'],['../md_running.html#autotoc_md160',1,'Restarting Cases']]],
  ['cavity_20problem_202d_4',['Lid-Driven Cavity Problem (2D)',['../md_examples.html#autotoc_md77',1,'']]],
  ['centerline_20velocities_5',['Centerline Velocities',['../md_examples.html#autotoc_md79',1,'']]],
  ['cfl_20dt_202d_6',['2D IBM CFL dt (2D)',['../md_examples.html#autotoc_md62',1,'']]],
  ['change_20model_7',['11. Phase Change Model',['../md_case.html#autotoc_md24',1,'']]],
  ['characteristic_20boundary_20conditions_8',['Generalized Characteristic Boundary conditions',['../md_case.html#autotoc_md32',1,'']]],
  ['cli_9',['Docker CLI',['../md_docker.html#autotoc_md40',1,'']]],
  ['clusters_20via_20apptainer_20singularity_10',['Using Supercomputers/Clusters via Apptainer/Singularity',['../md_docker.html#autotoc_md43',1,'']]],
  ['code_20api_20documentation_11',['Code/API Documentation',['../md_readme.html#autotoc_md152',1,'']]],
  ['coded_20patches_12',['Hard Coded Patches',['../md_case.html#autotoc_md9',1,'']]],
  ['command_20line_20arguments_13',['(Optional) Accepting command line arguments',['../md_case.html#autotoc_md3',1,'']]],
  ['compiler_20agnostic_20tools_14',['Compiler agnostic tools',['../md_gpuParallelization.html#autotoc_md139',1,'']]],
  ['compiler_20documentation_15',['Compiler Documentation',['../md_gpuParallelization.html#autotoc_md148',1,'']]],
  ['compiler_20options_16',['NVHPC Compiler Options',['../md_gpuParallelization.html#autotoc_md144',1,'']]],
  ['compiler_20tools_17',['Cray Compiler Tools',['../md_gpuParallelization.html#autotoc_md141',1,'']]],
  ['component_20inert_20shock_20tube_18',['1D Multi-Component Inert Shock Tube',['../md_examples.html#autotoc_md101',1,'']]],
  ['component_20reactive_20shock_20tube_19',['1D Multi-Component Reactive Shock Tube',['../md_examples.html#autotoc_md69',1,'']]],
  ['computation_20macros_20',['Computation Macros',['../md_gpuParallelization.html#autotoc_md130',1,'']]],
  ['computational_20domain_21',['2. Computational Domain',['../md_case.html#autotoc_md6',1,'']]],
  ['condition_22',['Condition',['../md_examples.html#autotoc_md68',1,'Final Condition'],['../md_examples.html#autotoc_md78',1,'Final Condition'],['../md_examples.html#autotoc_md94',1,'Final Condition'],['../md_examples.html#autotoc_md105',1,'Final Condition'],['../md_examples.html#autotoc_md54',1,'Initial Condition'],['../md_examples.html#autotoc_md65',1,'Initial Condition'],['../md_examples.html#autotoc_md70',1,'Initial Condition'],['../md_examples.html#autotoc_md84',1,'Initial Condition'],['../md_examples.html#autotoc_md91',1,'Initial Condition'],['../md_examples.html#autotoc_md102',1,'Initial Condition']]],
  ['condition_20and_20linear_20theory_23',['Condition and Linear Theory',['../md_examples.html#autotoc_md61',1,'Final Condition and Linear Theory'],['../md_examples.html#autotoc_md96',1,'Final Condition and Linear Theory']]],
  ['condition_20and_20result_24',['Initial Condition and Result',['../md_examples.html#autotoc_md87',1,'']]],
  ['condition_20density_25',['Condition Density',['../md_examples.html#autotoc_md73',1,'Final Condition (Density)'],['../md_examples.html#autotoc_md89',1,'Final Condition (Density)']]],
  ['condition_20patches_26',['Boundary Condition Patches',['../md_case.html#autotoc_md16',1,'']]],
  ['conditions_27',['Density Initial and Final Conditions',['../md_examples.html#autotoc_md75',1,'']]],
  ['conditions_28',['conditions',['../md_case.html#autotoc_md31',1,'Boundary conditions'],['../md_case.html#autotoc_md32',1,'Generalized Characteristic Boundary conditions']]],
  ['conservative_20variables_20ordering_29',['Conservative Variables Ordering',['../md_case.html#autotoc_md35',1,'']]],
  ['constant_20time_20stepping_30',['Constant Time-Stepping',['../md_case.html#autotoc_md17',1,'']]],
  ['containers_31',['Containers',['../md_docker.html',1,'Containers'],['../md_docker.html#autotoc_md41',1,'Details on Running Containers'],['../md_getting-started.html#autotoc_md121',1,'Using Containers']]],
  ['control_20macros_32',['Data Control Macros',['../md_gpuParallelization.html#autotoc_md132',1,'']]],
  ['coordinates_33',['16. Cylindrical Coordinates',['../md_case.html#autotoc_md29',1,'']]],
  ['coordinates_34',['Visualizing data in cylindrical coordinates',['../md_visualization.html#autotoc_md167',1,'']]],
  ['cpu_35',['CPU',['../md_expectedPerformance.html#autotoc_md111',1,'IBM Power9 CPU'],['../md_expectedPerformance.html#autotoc_md116',1,'IBM Power9 CPU']]],
  ['cray_20compiler_20tools_36',['Cray Compiler Tools',['../md_gpuParallelization.html#autotoc_md141',1,'']]],
  ['cray_20general_20options_37',['Cray General Options',['../md_gpuParallelization.html#autotoc_md142',1,'']]],
  ['cray_20openacc_20options_38',['Cray OpenACC Options',['../md_gpuParallelization.html#autotoc_md143',1,'']]],
  ['creating_20tests_39',['Creating Tests',['../md_testing.html#autotoc_md163',1,'']]],
  ['customizing_20the_20script_40',['Step 2: Customizing the script',['../md_visualization.html#autotoc_md172',1,'']]],
  ['cylindrical_20coordinates_41',['16. Cylindrical Coordinates',['../md_case.html#autotoc_md29',1,'']]],
  ['cylindrical_20coordinates_42',['Visualizing data in cylindrical coordinates',['../md_visualization.html#autotoc_md167',1,'']]]
];
