var searchData=
[
  ['data_20control_20macros_0',['Data Control Macros',['../md_gpuParallelization.html#autotoc_md132',1,'']]],
  ['data_20flow_1',['Data Flow',['../md_gpuParallelization.html#autotoc_md128',1,'']]],
  ['data_20in_20cylindrical_20coordinates_2',['Visualizing data in cylindrical coordinates',['../md_visualization.html#autotoc_md167',1,'']]],
  ['data_20output_3',['Serial data output',['../md_visualization.html#autotoc_md169',1,'']]],
  ['data_20type_20meanings_4',['Data Type Meanings',['../md_gpuParallelization.html#autotoc_md127',1,'']]],
  ['debugging_20tools_20and_20tips_20for_20gpus_5',['Debugging Tools and Tips for GPUs',['../md_gpuParallelization.html#autotoc_md138',1,'']]],
  ['definition_20of_20primitive_20variables_6',['Analytical Definition of Primitive Variables',['../md_case.html#autotoc_md8',1,'']]],
  ['density_7',['Density',['../md_examples.html#autotoc_md81',1,'Density'],['../md_examples.html#autotoc_md73',1,'Final Condition (Density)'],['../md_examples.html#autotoc_md89',1,'Final Condition (Density)']]],
  ['density_20initial_20and_20final_20conditions_8',['Density Initial and Final Conditions',['../md_examples.html#autotoc_md75',1,'']]],
  ['density_20norms_9',['Density Norms',['../md_examples.html#autotoc_md82',1,'']]],
  ['descriptions_10',['Descriptions',['../md_case.html#autotoc_md10',1,'Parameter Descriptions'],['../md_case.html#autotoc_md13',1,'Parameter Descriptions']]],
  ['desktop_20gui_11',['Docker Desktop GUI',['../md_docker.html#autotoc_md39',1,'']]],
  ['details_12',['Tag Details',['../md_docker.html#autotoc_md47',1,'']]],
  ['details_20on_20running_20containers_13',['Details on Running Containers',['../md_docker.html#autotoc_md41',1,'']]],
  ['docker_14',['Navigating Docker',['../md_docker.html#autotoc_md38',1,'']]],
  ['docker_20cli_15',['Docker CLI',['../md_docker.html#autotoc_md40',1,'']]],
  ['docker_20desktop_20gui_16',['Docker Desktop GUI',['../md_docker.html#autotoc_md39',1,'']]],
  ['docker_2emd_17',['docker.md',['../docker_8md.html',1,'']]],
  ['documentation_18',['Documentation',['../md_readme.html#autotoc_md152',1,'Code/API Documentation'],['../md_gpuParallelization.html#autotoc_md148',1,'Compiler Documentation'],['../md_readme.html',1,'Documentation'],['../md_gpuParallelization.html#autotoc_md126',1,'Macro API Documentation'],['../md_readme.html#autotoc_md151',1,'User Documentation']]],
  ['domain_19',['2. Computational Domain',['../md_case.html#autotoc_md6',1,'']]],
  ['driven_20cavity_20problem_202d_20',['Lid-Driven Cavity Problem (2D)',['../md_examples.html#autotoc_md77',1,'']]],
  ['droplet_202d_21',['Shock Droplet (2D)',['../md_examples.html#autotoc_md90',1,'']]],
  ['dt_202d_22',['2D IBM CFL dt (2D)',['../md_examples.html#autotoc_md62',1,'']]]
];
