var searchData=
[
  ['pace_20paraview_20server_0',['Step 3: Running pace-paraview-server',['../md_visualization.html#autotoc_md173',1,'']]],
  ['pace_20phoenix_1',['Remote Visualization on PACE Phoenix',['../md_visualization.html#autotoc_md170',1,'']]],
  ['papers_2',['Papers',['../md_papers.html',1,'']]],
  ['papers_2emd_3',['papers.md',['../papers_8md.html',1,'']]],
  ['parallelization_4',['GPU Parallelization',['../md_gpuParallelization.html',1,'']]],
  ['parameter_20descriptions_5',['Parameter Descriptions',['../md_case.html#autotoc_md10',1,'Parameter Descriptions'],['../md_case.html#autotoc_md13',1,'Parameter Descriptions']]],
  ['parameters_6',['Parameters',['../md_case.html#autotoc_md4',1,'']]],
  ['paraview_7',['Visualizing with Paraview',['../md_visualization.html#autotoc_md166',1,'']]],
  ['paraview_20server_8',['Step 3: Running pace-paraview-server',['../md_visualization.html#autotoc_md173',1,'']]],
  ['patch_20types_9',['Immersed Boundary Patch Types',['../md_case.html#autotoc_md34',1,'']]],
  ['patch_20types_10',['Patch types',['../md_case.html#autotoc_md33',1,'']]],
  ['patches_11',['Patches',['../md_case.html#autotoc_md7',1,'3. Patches'],['../md_case.html#autotoc_md12',1,'4. Immersed Boundary Patches'],['../md_case.html#autotoc_md16',1,'Boundary Condition Patches'],['../md_case.html#autotoc_md9',1,'Hard Coded Patches']]],
  ['perfectly_20stirred_20reactor_12',['Perfectly Stirred Reactor',['../md_examples.html#autotoc_md76',1,'']]],
  ['performance_13',['Performance',['../md_expectedPerformance.html',1,'']]],
  ['performance_14',['Figure of merit: Grind time performance',['../md_expectedPerformance.html#autotoc_md107',1,'']]],
  ['performance_20test_15',['Scaling and Performance test',['../md_examples.html#autotoc_md56',1,'']]],
  ['phase_20change_20model_16',['11. Phase Change Model',['../md_case.html#autotoc_md24',1,'']]],
  ['phoenix_17',['Remote Visualization on PACE Phoenix',['../md_visualization.html#autotoc_md170',1,'']]],
  ['point_202d_18',['2D Triple Point (2D)',['../md_examples.html#autotoc_md97',1,'']]],
  ['points_19',['Points',['../md_expectedPerformance.html#autotoc_md114',1,'16M Grid Points'],['../md_expectedPerformance.html#autotoc_md115',1,'64M Grid Points']]],
  ['portability_20',['Portability',['../md_docker.html#autotoc_md45',1,'For Portability'],['../md_docker.html#autotoc_md42',1,'Portability']]],
  ['post_20process_21',['Testing Post Process',['../md_testing.html#autotoc_md164',1,'']]],
  ['power9_20cpu_22',['Power9 CPU',['../md_expectedPerformance.html#autotoc_md111',1,'IBM Power9 CPU'],['../md_expectedPerformance.html#autotoc_md116',1,'IBM Power9 CPU']]],
  ['primitive_20variables_23',['Analytical Definition of Primitive Variables',['../md_case.html#autotoc_md8',1,'']]],
  ['primitive_20variables_20ordering_24',['Primitive Variables Ordering',['../md_case.html#autotoc_md36',1,'']]],
  ['problem_201d_25',['problem 1D',['../md_examples.html#autotoc_md53',1,'Lax shock tube problem (1D)'],['../md_examples.html#autotoc_md64',1,'Shu-Osher problem (1D)'],['../md_examples.html#autotoc_md83',1,'Titarev-Toro problem (1D)']]],
  ['problem_202d_26',['Lid-Driven Cavity Problem (2D)',['../md_examples.html#autotoc_md77',1,'']]],
  ['problem_202d_27',['Isentropic vortex problem (2D)',['../md_examples.html#autotoc_md80',1,'']]],
  ['process_28',['Testing Post Process',['../md_testing.html#autotoc_md164',1,'']]],
  ['profiling_29',['GPU Profiling',['../md_running.html#autotoc_md157',1,'']]]
];
