var searchData=
[
  ['scaling_0',['Scaling',['../md_examples.html#autotoc_md58',1,'Strong Scaling'],['../md_examples.html#autotoc_md57',1,'Weak Scaling']]],
  ['scaling_1',['scaling',['../md_expectedPerformance.html#autotoc_md112',1,'Strong scaling'],['../md_expectedPerformance.html#autotoc_md108',1,'Weak scaling']]],
  ['scaling_20and_20performance_20test_2',['Scaling and Performance test',['../md_examples.html#autotoc_md56',1,'']]],
  ['schlieren_20at_20final_20time_3',['Numerical Schlieren at Final Time',['../md_examples.html#autotoc_md98',1,'']]],
  ['script_4',['Step 2: Customizing the script',['../md_visualization.html#autotoc_md172',1,'']]],
  ['serial_20data_20output_5',['Serial data output',['../md_visualization.html#autotoc_md169',1,'']]],
  ['server_6',['Step 3: Running pace-paraview-server',['../md_visualization.html#autotoc_md173',1,'']]],
  ['setting_20up_20your_20environment_7',['Step 1: Setting up your Environment',['../md_visualization.html#autotoc_md171',1,'']]],
  ['setup_8',['10. Velocity Field Setup',['../md_case.html#autotoc_md23',1,'']]],
  ['shell_9',['Interactive Shell',['../md_docker.html#autotoc_md44',1,'']]],
  ['shock_203d_10',['IBM Bow Shock (3D)',['../md_examples.html#autotoc_md104',1,'']]],
  ['shock_20droplet_202d_11',['Shock Droplet (2D)',['../md_examples.html#autotoc_md90',1,'']]],
  ['shock_20tube_12',['Shock Tube',['../md_examples.html#autotoc_md101',1,'1D Multi-Component Inert Shock Tube'],['../md_examples.html#autotoc_md69',1,'1D Multi-Component Reactive Shock Tube']]],
  ['shock_20tube_20problem_201d_13',['Lax shock tube problem (1D)',['../md_examples.html#autotoc_md53',1,'']]],
  ['shu_20osher_20problem_201d_14',['Shu-Osher problem (1D)',['../md_examples.html#autotoc_md64',1,'']]],
  ['simulation_20algorithm_15',['6. Simulation Algorithm',['../md_case.html#autotoc_md15',1,'']]],
  ['singularity_16',['Using Supercomputers/Clusters via Apptainer/Singularity',['../md_docker.html#autotoc_md43',1,'']]],
  ['skeleton_17',['Basic Skeleton',['../md_case.html#autotoc_md2',1,'']]],
  ['slurm_20job_18',['Slurm Job',['../md_docker.html#autotoc_md46',1,'']]],
  ['smoothing_19',['Elliptic Smoothing',['../md_case.html#autotoc_md11',1,'']]],
  ['source_20',['8. Acoustic Source',['../md_case.html#acoustic-source',1,'']]],
  ['started_21',['Getting Started',['../md_getting-started.html',1,'']]],
  ['state_22',['Liutex visualization at transitional state',['../md_examples.html#autotoc_md100',1,'']]],
  ['step_201_3a_20setting_20up_20your_20environment_23',['Step 1: Setting up your Environment',['../md_visualization.html#autotoc_md171',1,'']]],
  ['step_202_3a_20customizing_20the_20script_24',['Step 2: Customizing the script',['../md_visualization.html#autotoc_md172',1,'']]],
  ['step_202d_25',['Step 2D',['../md_examples.html#autotoc_md88',1,'Backward Facing Step (2D)'],['../md_examples.html#autotoc_md72',1,'Forward Facing Step (2D)']]],
  ['step_203_3a_20running_20pace_20paraview_20server_26',['Step 3: Running pace-paraview-server',['../md_visualization.html#autotoc_md173',1,'']]],
  ['stepping_27',['Stepping',['../md_case.html#autotoc_md18',1,'Adaptive Time-Stepping'],['../md_case.html#autotoc_md17',1,'Constant Time-Stepping']]],
  ['stirred_20reactor_28',['Perfectly Stirred Reactor',['../md_examples.html#autotoc_md76',1,'']]],
  ['strong_20scaling_29',['Strong Scaling',['../md_examples.html#autotoc_md58',1,'']]],
  ['strong_20scaling_30',['Strong scaling',['../md_expectedPerformance.html#autotoc_md112',1,'']]],
  ['structure_31',['Tag Structure',['../md_docker.html#autotoc_md49',1,'']]],
  ['sub_20grid_20bubble_20models_32',['9. Sub-grid Bubble Models',['../md_case.html#autotoc_md20',1,'']]],
  ['suite_33',['Running the Test Suite',['../md_getting-started.html#autotoc_md122',1,'']]],
  ['supercomputers_20clusters_20via_20apptainer_20singularity_34',['Using Supercomputers/Clusters via Apptainer/Singularity',['../md_docker.html#autotoc_md43',1,'']]],
  ['support_35',['Architecture Support',['../md_docker.html#autotoc_md51',1,'']]],
  ['supports_36',['Acoustic Supports',['../md_case.html#acoustic-supports',1,'']]],
  ['synchronization_20macros_37',['Synchronization Macros',['../md_gpuParallelization.html#autotoc_md134',1,'']]]
];
