var searchData=
[
  ['tag_20details_0',['Tag Details',['../md_docker.html#autotoc_md47',1,'']]],
  ['tag_20structure_1',['Tag Structure',['../md_docker.html#autotoc_md49',1,'']]],
  ['tags_2',['Example Tags',['../md_docker.html#autotoc_md50',1,'']]],
  ['taylor_20green_20vortex_203d_3',['Taylor-Green Vortex (3D)',['../md_examples.html#autotoc_md93',1,'']]],
  ['taylor_20instability_202d_4',['Rayleigh-Taylor Instability (2D)',['../md_examples.html#autotoc_md95',1,'']]],
  ['taylor_20instability_203d_5',['Rayleigh-Taylor Instability (3D)',['../md_examples.html#autotoc_md60',1,'']]],
  ['test_6',['Scaling and Performance test',['../md_examples.html#autotoc_md56',1,'']]],
  ['test_202d_7',['2D Riemann Test (2D)',['../md_examples.html#autotoc_md74',1,'']]],
  ['test_20suite_8',['Running the Test Suite',['../md_getting-started.html#autotoc_md122',1,'']]],
  ['testing_9',['Testing',['../md_testing.html',1,'']]],
  ['testing_20post_20process_10',['Testing Post Process',['../md_testing.html#autotoc_md164',1,'']]],
  ['testing_2emd_11',['testing.md',['../testing_8md.html',1,'']]],
  ['tests_12',['Creating Tests',['../md_testing.html#autotoc_md163',1,'']]],
  ['the_20script_13',['Step 2: Customizing the script',['../md_visualization.html#autotoc_md172',1,'']]],
  ['the_20test_20suite_14',['Running the Test Suite',['../md_getting-started.html#autotoc_md122',1,'']]],
  ['theory_15',['Theory',['../md_examples.html#autotoc_md61',1,'Final Condition and Linear Theory'],['../md_examples.html#autotoc_md96',1,'Final Condition and Linear Theory']]],
  ['time_16',['Numerical Schlieren at Final Time',['../md_examples.html#autotoc_md98',1,'']]],
  ['time_20performance_17',['Figure of merit: Grind time performance',['../md_expectedPerformance.html#autotoc_md107',1,'']]],
  ['time_20stepping_18',['Time Stepping',['../md_case.html#autotoc_md18',1,'Adaptive Time-Stepping'],['../md_case.html#autotoc_md17',1,'Constant Time-Stepping']]],
  ['tips_20for_20gpus_19',['Debugging Tools and Tips for GPUs',['../md_gpuParallelization.html#autotoc_md138',1,'']]],
  ['titarev_20toro_20problem_201d_20',['Titarev-Toro problem (1D)',['../md_examples.html#autotoc_md83',1,'']]],
  ['tools_21',['Cray Compiler Tools',['../md_gpuParallelization.html#autotoc_md141',1,'']]],
  ['tools_22',['tools',['../md_gpuParallelization.html#autotoc_md139',1,'Compiler agnostic tools'],['../md_gpuParallelization.html#autotoc_md140',1,'OpenMP tools']]],
  ['tools_20and_20tips_20for_20gpus_23',['Debugging Tools and Tips for GPUs',['../md_gpuParallelization.html#autotoc_md138',1,'']]],
  ['toro_20problem_201d_24',['Titarev-Toro problem (1D)',['../md_examples.html#autotoc_md83',1,'']]],
  ['transitional_20state_25',['Liutex visualization at transitional state',['../md_examples.html#autotoc_md100',1,'']]],
  ['triple_20point_202d_26',['2D Triple Point (2D)',['../md_examples.html#autotoc_md97',1,'']]],
  ['tube_27',['Tube',['../md_examples.html#autotoc_md101',1,'1D Multi-Component Inert Shock Tube'],['../md_examples.html#autotoc_md69',1,'1D Multi-Component Reactive Shock Tube']]],
  ['tube_20problem_201d_28',['Lax shock tube problem (1D)',['../md_examples.html#autotoc_md53',1,'']]],
  ['turbulent_20mixing_20layer_203d_29',['3D Turbulent Mixing layer (3D)',['../md_examples.html#autotoc_md99',1,'']]],
  ['type_20meanings_30',['Data Type Meanings',['../md_gpuParallelization.html#autotoc_md127',1,'']]],
  ['types_31',['Immersed Boundary Patch Types',['../md_case.html#autotoc_md34',1,'']]],
  ['types_32',['Patch types',['../md_case.html#autotoc_md33',1,'']]]
];
